name: richardcoulson
favicon: null
layout_spectrum: 0.8408541379030794
typography_spectrum: 0.7206181772053242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8579799304716289
  lightness: 0.4188271351158619
  saturation: 0.6190965485293418
  rhythmicContrast: 0.395349943311885
purpose: []
